### ISSUE TITLE
Per-key actuation label prevents setting indicator color

### ISSUE THREAD

**Issue by mikey-dg** [WootingKb/wootility-issues#125]
It does not seem to be possible to set the indicator color of a key (e.g. Fn, Caps, etc) without first removing any per-key actuation level for that key.  Attempting to left-click the indicator circle simply sets the key's primary color, and right-clicking to retrieve the color also grabs the key's primary color.  I'd guess that mouse interactions are being passed by the label to the key object rather than the indicator circle object.

This is what a key with an indicator color and a per-key actuation level looks like on my system (Win 7, Wootility v4.34, Wooting 2 HE v2.4.6):
![caps](https://user-images.githubusercontent.com/96163084/146128837-7db848c1-330a-4f03-8151-89c4a2814207.png)

Unless the location of the key actuation level label is a problem specific to my system configuration, it should probably be moved to the upper-left or lower-right of the key image for readability purposes, nevermind the functional problem it's causing.

Steps to reproduce:
1. Set a per-key actuation level for a key with an indicator color
2. Go to the color tab and attempt to set or retrieve the indicator color by left- or right-clicking on the circle

I don't recall this being a problem in previous Wootility versions, and I've had a per-key level on Caps the whole time, so it may be something that's just cropped in 4.3.4.

**Comment by mikey-dg** [comment]
Today I also noticed that the per-key actuation screen itself moves the key-name labels down too far - this is what it looks like on my system (Wootility v4.3.5 on Windows 7 @ 1080p):
![caps-under](https://user-images.githubusercontent.com/96163084/147375235-17b96102-8dbb-4085-9ec4-285ff884a9e8.png)

The layout of key images with a per-key actuation label could be unified between all of the keyboard screens to look something like this, with the key name label moved down 4px and the actuation label shown in the better font that's currently used in the per-key actuation screen, oriented up 1px and just to the left of the indicator color:
![caps-mockup-right](https://user-images.githubusercontent.com/96163084/147375759-5189da94-0d5a-48ba-a779-52c192f83ffb.png)

And here's what the same scheme would look like on smaller keys with taller ending characters:
![fn-mockup](https://user-images.githubusercontent.com/96163084/147375747-756165cd-fbe1-4480-9cb1-0ecb08cd3497.png) ![scrl-mockup](https://user-images.githubusercontent.com/96163084/147375748-8130fc2c-323d-463a-9009-a2628fd6e7ea.png)
While it's a bit cramped on a standard-size key, it's still much more readable than on any of the current screens.  I'm not a graphic designer, and this is just a quick mockup, so it could certainly be finessed a bit better than this.

**Comment by simon-wh** [comment]
This has been resolved in development and will be included in the next v4.3 update which we hope to have out tomorrow all being well

**Comment by mikey-dg** [comment]
> This has been resolved in development and will be included in the next v4.3 update which we hope to have out tomorrow all being well

The color tab looks to be working fine now in 4.3.8, but the second part of the issue persists: on the per key actuation tab, the key label is still moved down below the lower border of the key image, making most key names unreadable.
