### ISSUE TITLE
Wootility fails to read RGB effect setting from keyboard profiles / RGB effects cannot be disabled with the Static button

### ISSUE THREAD

**Issue by mikey-dg** [WootingKb/wootility-issues#250]
The latest version of the Wootility (4.6.7) does not ever seem to read which RGB effect is enabled for a given keyboard profile, either on start-up or on switching to a profile (via either the profile selection keys or the Wootility profile selector).  Regardless of which effect is enabled on the keyboard, when switching away from and back to a profile with RGB effects or restarting the Wootility the application shows 'Static' as the configured RGB effect, despite the effect clearly still being active on the keyboard.

This happens with both digital and analog profiles, active and inactive profiles, and with seemingly all RGB effects.

Selecting Static to disable the RGB effect on a given profile has no effect even if another RGB effect is selected and saved first, and the initially-set RGB effect cannot be disabled via any means other than enabling Tachyon Mode.

Even worse, switching to a different effect sometimes crashes the keyboard, causing it to revert to a fully default profile when re-plugged - this happened 2 times out of ~10 attempts to switch to another RGB effect.  Fortunately, reconnecting to the Wootility seems to reliably restore the last-saved version of the profile.

The keyboard is connected directly to a USB3 port on the PC, and there are no other unusual issues occurring.

This is the affected digital profile backed up before adding the RGB effect:
31f1c085b180c71b0cc7bda8bdb01dd62f04

And after adding the un-removable AOE effect:
84b7dc6adaef4ebc17a92816886b6691ebd9

(The variations in color mapping are compensatory for the keyboard's lack of user color calibration)
I assume the Wootility profile data does somehow contain the un-removable RGB effect, since switching to the backed-up profile removes the RGB effect from the keyboard even when Tachyon Mode is disabled in that profile, and switching to a post-RGB duplicate profile still silently re-enables the RGB effect.

1. Enable an RGB effect in the Wootility and save to the keyboard
2. Switch to a different profile, and then switch back
3. Observe that Static is selected in the Wootility while the previously-set RGB effect is still active on the keyboard
4. Select a different RGB effect and save to the keyboard
5. If the keyboard didn't lock up, re-select Static in the Wootility, save to the keyboard
6. Observe that the initially-set RGB effect is still active on the keyboard

Wootility: v4.6.7
Keyboard: Wooting 2 HE v2.7.1 (and 2.7.2)

**Comment by simon-wh** [comment]
I've seen a couple other reports of behaviour like this. I'll be able to look into it deeply at the start of next week and hopefully get it resolved

Re: v4.6.9 and Windows 7. I wasn't aware that Electron/Chromium had deprecated support for Windows 7/8/8.1 (and I had updated electron to the latest). I've just released v4.6.10 which uses Electron v22, which is the most recent to still support Windows 7

**Comment by simon-wh** [comment]
Sorry for the delayed update, I believe this should be resolved with Wootility v4.6.11. Please let me know if you're still experiencing issues on this version

**Comment by mikey-dg** [comment]
It seems to be partly resolved - it's reading the keyboard profile's RGB setting properly both on load and profile switch, and is never showing a mismatch between the effect on the keyboard and the effect selected in the menu.

However, if I try to select Static directly from from the saved effect, nothing happens except saving/undoing becoming available.  Repeatedly selecting Static from the saved effect changes nothing, but continues to add undo layers.  Selecting a different effect works, but the first time I select Static from any effect it will jump back to the saved effect instead.  The only way to actually disable RGB effects is to select a new effect, then Static, then another effect, and finally Static a second time.

**Comment by eluvex** [comment]
hello i just got my wooting two he, however i have the exact same problem. when turning on my computer the static effect loads for my profile but no matter what even after i open wootility, if i press mode and switch profiles. nothing happens. i have the same static on the other profile so im not sure if its not switching at all or just not loading the rgb effects. i have trail set on the first one and it does not work, and RT display on the second one, neither of them load when switched to. if i unplug and plug it back it in it completely resets my rgb and i must configure it again. i am not sure how to solve this.

**Comment by simon-wh** [comment]
@mikey-dg I just released a new beta firmware `v2.7.3-beta.4` which includes fixes for the Two HE AVR and Lekker Edition which I hope should resolve the remaining issues you're having.

@eluvex It may be worthwhile for you to try it as well

**Beta Links**:
- **Wootility Web**: https://beta.wootility.io/
- [Windows](https://api.wooting.io/public/wootility/download?os=win&branch=lekker&channel=beta)
- [Mac (Intel)](https://api.wooting.io/public/wootility/download?os=mac&branch=lekker&channel=beta)
- [Mac (Apple Silicon)](https://api.wooting.io/public/wootility/download?os=mac&branch=lekker&platform=arm64&channel=beta)
- [Linux](https://api.wooting.io/public/wootility/download?os=linux&branch=lekker&channel=beta)

**Comment by eluvex** [comment]
Same issue still happening.

**Comment by mikey-dg** [comment]
Yeah, same here, no meaningful change.  All recent Wootility versions start up showing the correct RGB effect, which is good.  But the other odd issues are still present any time you connect a keyboard to the Wootility whose loaded profile has a set RGB effect.

In Wootility Web v4.6.15-beta with the 2.7.3-beta.3 firmware (2HE AVR), immediately after connecting to the keyboard:
* Attempting to select Static any number of times does absolutely nothing.  No button pulse effect, the selector position doesn't change, and it doesn't even create an undo layer; basically the button presses themselves are being nullified.  Maybe the RGB button checks think the UI is already set to Static, even though it's correctly showing the keyboard's actual effect as selected?
* Selecting another effect will switch the effect selector to it and show that effect's settings, but the keyboard doesn't update with the new effect.  Continued selection of other effects or changing the newly-selected effect's settings does nothing but create undo layers.
* Selecting another effect, then Static once (which only pulses the button and creates an undo layer), and then selecting Static or another effect again actually changes the keyboard's RGB effect and updates the selector.  Static always requires a repeat press in this case.

After selecting any one item in the RGB effect panel that creates an undo layer (another effect), and pressing undo all the way back to the loaded state:
* Selecting Static once does nothing but pulse the button and add an undo layer, and requires a second press to clear the RGB effect on the keyboard.
* Selecting another effect works as expected.

One exception: when selecting another effect, then Static twice, and then undoing the whole stack, it returns to the state where any number of Static presses are completely ignored with no UI feedback at all.

Static (and only Static) always requires two sequential presses to take effect the first time, and is only possible to select at all after attempting to select another effect.  Once it's been actually set on the keyboard with a second press, switching to another effect and back to Static only requires one press.  At that point, everything in the RGB UI begins working as expected until the keyboard is re-connected, even through profile switches.  All of this seems to suggest that upon startup or undoing to startup state after successfully selecting Static, some part of the UI thinks it's on Static when it isn't.

None of this behavior is observed when connecting the keyboard to the Wootility with the RGB set to Static, and in that case everything seems to work fine.

I also just checked some of this with the stable Wootility v4.6.15, and the total ignoring of Static presses is not present on load, but is once you select another effect, Static twice, and then undo everything.  Everything else seems to behave the same.

---
Unrelated, and I'm not sure if it's expected or intentional, but when removing and re-connecting the keyboard in the offline Wootility, it never re-detects devices (even when exiting Demo Mode and selecting Initialise a Device), and you have to either restart the Wootility or re-plug the keyboard, where Wootility Web offers a Connect Device option in the device drop-down that re-detects without any hassle.

**Comment by eluvex** [comment]
Can we please get an update on this
