### ISSUE TITLE
\ key is mapped twice in the dvorak preset

### ISSUE THREAD

**Issue by werdnaa87** [WootingKb/wootility-issues#28]
**Describe the bug**
The default DVORAK layout is incorrect. There are 2 \ keys and no / key

**To Reproduce**
1. Go to remap
2. Click on presets
3. Look at DVORAK
4. You will notice that there are 2 \ keys mapped

**Screenshots / Video**
What currently gets set:
![image](https://user-images.githubusercontent.com/64870117/81733507-2236a800-9460-11ea-8e23-462afa5e2911.png)

What it should be:
![image](https://user-images.githubusercontent.com/64870117/81733561-37133b80-9460-11ea-95d9-38d970672da2.png)

Notice that the \ key is both on the board twice and the /? key is not there at all

**Desktop (please complete the following information):**
 - OS: Windows 10

**Wootility and Firmware version**
3.5.5-beta

**Keyboard Type**
I have a Wooting one, but I assume a two is the same

**Comment by PastaJ36** [comment]
A little late, but thanks for creating the issue. We'll fix it for the next beta

**Comment by Rocky04** [comment]
Same problem for ISO UK extended.

![image](https://user-images.githubusercontent.com/5910569/84142681-7fb91700-aa55-11ea-8db2-6422bdfaa6a4.png)

**Comment by Rocky04** [comment]
This bug is still present in the seconds Beta Wootility 3.5.6.

**Comment by simon-wh** [comment]
ISO Layouts have been fixed and will be included in >=v3.5.7

**Comment by Rocky04** [comment]
I still see the two keys with backslash for ISO UK extended.

**Comment by simon-wh** [comment]
What keyboard layout do you have selected in your system? I use UK ISO normally and have it set to that on my system. If you don't have gb then it won't display on the UI correctly as the key to the left of Enter is \ with US and #~ with UK, so if Wootility thinks you are using US for example then it will display backslashes for both the key right of shift and the key left of Enter. When in reality, if your system is set to UK layout then the key left of Enter should input #~ not \

**Comment by Rocky04** [comment]
It works for ISO UKl:
![image](https://user-images.githubusercontent.com/5910569/85046120-463c8600-b190-11ea-84ec-5f679b6dce0f.png)

But it don't work for ISO UKX (UK extended):
![image](https://user-images.githubusercontent.com/5910569/85046231-6a986280-b190-11ea-9241-9859b897f01a.png)

**Comment by simon-wh** [comment]
Do they input correctly when applied? I think this looks more like a display issue, where it doesn't recognise UKX as UK when displaying localised key labels

**Comment by Rocky04** [comment]
Yes, the inputs are correct. As far as I can tell UKX looks exactlz the same as UK but it adds special commands to it to archive "ŵ" by pressing "Alt Gr" and "6" and then "w".

So if you detect UKX use the UK layout and it's fine.

**Comment by simon-wh** [comment]
> Yes, the inputs are correct. As far as I can tell UKX looks exactly the same as UK but it adds special commands to it to archive "ŵ" by pressing "Alt Gr" and "6" (to get "^") and then "w" to allow the user to enter a wide variety of diacritics. So besides the diacritics it's the same I guess.
> 
> So if you detect UKX use the UK layout and it's fine.
> 
> _So yes this seems to be indeed just a display issue of the Wootility. I can't tell why it don't uses the corrent layout._

I was able to easily add the UKX to the mapping for UK, however, I feel like there's probably quite a fair number of layouts which aren't currently detected properly, so maybe we should have a general issue for layout detections

**Comment by Rocky04** [comment]
I think it would be great to decouple the layout information into a separate file so that users can modify or add new layouts to the Wootility by their own. So you don't need to handle every language and users can maybe provide them to you as new defaults or at least to other users.

Because of missing insides here I would suggest that you only show languages you had confirmed to be correctly and just show a default layout if all the layout which are unknown. Then you need to check at least the standard common ones. A good indication for a priority list of languages should be the sales volumne.

**Comment by PastaJ36** [comment]
We use [this](https://github.com/microsoft/node-native-keymap) library for the keyboard layout detection, but their Windows detection uses some old hexadecimal identifier system. I've opened an issue if they can use the [new api](https://docs.microsoft.com/en-us/uwp/api/windows.globalization.language.currentinputmethodlanguagetag?view=winrt-19041), that should prevent any layout language issue.
