### ISSUE TITLE
The German "Settings" text clips off the settings button

### ISSUE THREAD

**Issue by DarrenVs** [WootingKb/wootility-issues#46]
**Describe the bug**
If you set your Wootility language to German (Deutsch), the "Settings" text clips off the button.

**To Reproduce**
1. Change the Wootility language to `Deutsch`
2. Notice the `Einstellungen` text clipping off the Settings button

**Image**
![image](https://user-images.githubusercontent.com/2780639/85279990-97e25a80-b487-11ea-83f5-1b957e7cdcbb.png)

---

**Desktop**
 - OS: Windows 10

**Wootility and Firmware versions**

- Frimware: `1.29.0`
- Wootility: `3.5.7-alpha`

**Keyboard Type**

- Wooting One

**Comment by Rocky04** [comment]
The sizes are fixed so this is a general problem and not related to a specific language anyway.

**Comment by PastaJ36** [comment]
Centered everything "fixed" the overflow issues, thanks. It's consistent in all languages now.

This doesn't fix it for future long text, but we're not sure how to best solve it in every case. I'm afraid it will just be a case by case. Unless we adjust font sizes, but that might make everything look worse.

![image](https://user-images.githubusercontent.com/7443105/85607331-4c30dc00-b654-11ea-91f2-c147d086a76b.png)

**Comment by Rocky04** [comment]
The app is basically just a web page, so it should be possible to set a minimal size and add an option to allow the fields to use as much space as they need. So that elements have no max size.

Or course you would need to add a fallback if the current window size is lesser than the size needed for the window, then you would add scroll bars. So normally I woudn't allow that unless the screen size is not big enough. So that the Wootility windows is always big enough to show everything.
